# Generated by Django 3.1.3 on 2024-05-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('image', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
