# Generated by Django 3.1.3 on 2024-05-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
