# Generated by Django 3.1.3 on 2024-05-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0005_auto_20240514_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='color',
        ),
    ]
